### ISSUE TITLE
ISk5MT174 - TimeoutError: Read in SerialTransport timed out

### ISSUE THREAD

**Issue by hadahop** [pwitab/iec62056-21#14]
I would like to read the data from the MT174 smart meter via the optical interface using the Weidmann 'IR Schreib/Lesekopf USB (Optokopf)', but I get an error message

```python
#!/usr/bin/python3

from iec62056_21.client import Iec6205621Client
import logging

# set up logging so you get a bit nicer printout of what is happening.
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s,%(msecs)d %(levelname)s: %(message)s",
    datefmt="%H:%M:%S",
)
client = Iec6205621Client.with_serial_transport(port='/dev/ttyUSB0')
client.connect()
print(client.standard_readout())
```

**Errormessage**
```txt
09:53:52,112 INFO: Staring init sequence
09:53:52,112 INFO: Sending request message: RequestMessage(device_address='')
09:53:52,218 DEBUG: Sent b'/?!\r\n' over transport: SerialTransport
09:53:52,218 DEBUG: Resting for 0.25 seconds
09:53:52,893 DEBUG: Received b'/ISk5MT174-0001\r\n' over transport: SerialTransport
09:53:52,893 INFO: Received identification message: IdentificationMessage(identification='T174-0001', manufacturer='ISk', switchover_baudrate_char='5')
09:53:52,893 INFO: Sending AckOptionsSelect message: AckOptionSelectMessage(baud_char='5', mode_char='0')
09:53:52,998 DEBUG: Sent b'\x06050\r\n' over transport: SerialTransport
09:53:52,998 DEBUG: Resting for 0.025 seconds
09:53:53,524 INFO: Reading standard readout from device.
Traceback (most recent call last):
  File "test2.py", line 17, in <module>
    print(client.standard_readout())
  File "/usr/local/lib/python3.8/dist-packages/iec62056_21/client.py", line 183, in standard_readout
    response = self.read_response()
  File "/usr/local/lib/python3.8/dist-packages/iec62056_21/client.py", line 296, in read_response
    data = self.transport.read()
  File "/usr/local/lib/python3.8/dist-packages/iec62056_21/transports.py", line 58, in read
    raise TimeoutError(f"Read in {self.__class__.__name__} timed out")
TimeoutError: Read in SerialTransport timed out
```
When I query the interface with the following script, I get data.

```
#!/usr/bin/env python3
import serial
import time

SERIALPORT = "/dev/ttyUSB0"
BAUDRATE = 300

ser = serial.Serial(SERIALPORT, BAUDRATE, serial.SEVENBITS, serial.PARITY_EVEN)
ser.write(b"\x2F\x3F\x21\x0D\x0A")

time.sleep(0.5)
numberOfLine = 0

while True:
  response = ser.readline()
  print(response)
  numberOfLine = numberOfLine + 1
  if (numberOfLine >= 11):
     break
ser.close()
```
Results:
```
b'ISk5MT174-0001\r\n'
 b'\x020.9.1(150802)\r\n'
 b'0.9.2(1200702)\r\n'
 b'0.0.0(00339188)\r\n'
 b'0.2.0(1.03)\r\n'
 b'C.1.6(FDF5)\r\n'
 b'1.8.1(0011400.587*kWh)\r\n'
 b'1.8.2(0023806.592*kWh)\r\n'
 b'2.8.1(0015608.024*kWh)\r\n'
 b'2.8.2(0000900.569*kWh)\r\n'
 b'F.F.0(0000000)\r\n'
```
What can I do so that I can get all the data?

**Comment by Krolken** [comment]
Hi

It seems your meter is using protocol mode A instead of C, that I have focused this library on so far.

In protocol mode A there is no baudrate switching so everything is still on 300 baud and the data is returned directly after the init request is send.

But you should be able to use the public functions of the client to read the data properly.

```python
client.send_init_request() 
identification = client.read_identification() # Read the first line as the identification
data = client.read_response()  # Reads the data response 
```

**Comment by hadahop** [comment]
@Krolken 
Thanks for your information, now it is working 👍 

```python
#!/usr/bin/python3

from iec62056_21.client import Iec6205621Client
import logging

# set up logging so you get a bit nicer printout of what is happening.
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s,%(msecs)d %(levelname)s: %(message)s",
    datefmt="%H:%M:%S",
)

client = Iec6205621Client.with_serial_transport(port='/dev/ttyUSB0')
client.connect()

client.send_init_request()
identification = client.read_identification() # Read the first line as the identification
data = client.read_response()  # Reads the data response
```

Results:
same as response = ser.readline()...

```txt
16:18:27,247 DEBUG: Received 
b'\x020.9.1(161710)\r\n
0.9.2(1200707)\r\n
0.0.0(00339188)\r\n
0.2.0(1.03)\r\n
C.1.6(FDF5)\r\n
1.8.1(0011414.755*kWh)\r\n
1.8.2(0023842.912*kWh)\r\n
2.8.1(0015660.611*kWh)\r\n
2.8.2(0000909.192*kWh)\r\n
F.F.0(0000000)\r\n
!\r\n\
x03=' over transport: SerialTransport
```

**Comment by Krolken** [comment]
great :)

Use the `.data` on the `AnswerResponse` to get a list of all `DataSet`s. 

So `data.data` in your code.
